{% set version = "0.3.2" %}

package:
  name: openblas_multipkg
  version: {{ version }}

source:
  fn: openblas-{{ version }}.tar.gz
  url: https://github.com/xianyi/OpenBLAS/archive/v{{ version }}.tar.gz
  sha256: e8ba64f6b103c511ae13736100347deb7121ba9b41ba82052b1a018a65c0cb15

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage('openblas', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("fortran") }}
    - perl
    - cmake                      # [win]
    - curl                       # [win]
    - jom                        # [win]

outputs:

  - name: libopenblas
    files:
      - lib/*.so               # [linux]
      - lib/libopenblas.so.0   # [linux]
      - lib/*.dylib            # [osx]
    about:
      home: http://www.openblas.net/
      license: BSD
      license_file: LICENSE
      summary: An Optimized BLAS library
      description: |
        OpenBLAS is based on GotoBLAS2 1.13 BSD version.
      doc_url: http://www.openblas.net/
      doc_source_url: https://github.com/xianyi/OpenBLAS/blob/develop/README.md
      dev_url: https://github.com/xianyi/OpenBLAS

  - name: libopenblas-static
    files:
      - lib/*.a
    about:
      summary: OpenBLAS static libraries.

  - name: openblas-devel
    files:
      - include
      - lib/pkgconfig
      - lib/cmake
      - site.cfg
    run_exports:
      - {{ pin_subpackage('libopenblas', max_pin='x.x.x') }}
    requirements:
      run:
        - {{ pin_subpackage('libopenblas', max_pin='x.x.x') }}
    about:
      summary: OpenBLAS headers and libraries for developing software that used OpenBLAS.

  # openblas meta-package. It is better to require openblas-devel or libopenblas
  - name: openblas
    requirements:
      run:
        - {{ pin_subpackage('openblas', max_pin='x.x.x') }}
        - {{ pin_subpackage('openblas-devel', max_pin='x.x.x') }}
    about:
      home: http://www.openblas.net/
      license: BSD
      license_file: LICENSE
      summary: An Optimized BLAS library
      description: |
        OpenBLAS is based on GotoBLAS2 1.13 BSD version.
      doc_url: http://www.openblas.net/
      doc_source_url: https://github.com/xianyi/OpenBLAS/blob/develop/README.md
      dev_url: https://github.com/xianyi/OpenBLAS

test:
  commands:
    - test -f ${PREFIX}/lib/libopenblas.a                            # [unix]
    - python -c "import ctypes; ctypes.cdll['${PREFIX}/lib/libopenblas${SHLIB_EXT}']"  # [unix]
    - if not exist %PREFIX%\\Library\\lib\\openblas.lib exit 1    # [win]

extra:
  recipe-maintainers:
    - gillins
    - groutr
    - jakirkham
    - jschueller
    - isuruf
    - msarahan
