{% set version = "0.3.29" %}
{% set sha_hash = "38240eee1b29e2bde47ebb5d61160207dc68668a54cac62c076bb5032013b1eb" %}

package:
  name: openblas_multipkg
  version: {{ version }}

source:
  url: https://github.com/OpenMathLib/OpenBLAS/archive/v{{ version }}.tar.gz
  sha256: {{ sha_hash }}

build:
  number: 1

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("fortran") }}
    - perl
    - cmake                      # [win]
    - curl                       # [win]
    - jom                        # [win]
    - make                       # [unix]
    - objconv                    # [osx]
outputs:
  - name: libopenblas
    files:
      - lib/libblas{{ SHLIB_EXT }}    # [unix]
      - lib/libcblas{{ SHLIB_EXT }}   # [unix]
      - lib/liblapack{{ SHLIB_EXT }}  # [unix]
      - lib/libopenblas*.so*          # [linux]
      - lib/libopenblas*.dylib        # [osx]
      - Library/bin/openblas.dll           # [win]
    requirements:
      build:
        - {{ stdlib("c") }}
        - {{ compiler("c") }}
        - {{ compiler("fortran") }}
    test:
      requires:
        - python      # [unix]
      commands:
        - test -f ${PREFIX}/lib/libopenblasp-r{{ version }}{{ SHLIB_EXT }}                                    # [not win]
        - nm -g ${PREFIX}/lib/libopenblasp-r{{ version }}{{ SHLIB_EXT }} | grep dsecnd                        # [osx and build_platform=="osx-64"]
        - python -c "import ctypes; ctypes.cdll['${PREFIX}/lib/libopenblasp-r{{ version }}{{ SHLIB_EXT }}']"  # [not win]
        - if not exist %PREFIX%\\Library\\bin\\openblas.dll exit 1                                            # [win]

    about:
      home: https://www.openblas.net/
      license: BSD-3-Clause
      license_file: LICENSE
      license_family: BSD
      summary: An Optimized BLAS library
      description: OpenBLAS is based on GotoBLAS2 1.13 BSD version.
      doc_url: https://www.openblas.net/
      doc_source_url: https://github.com/xianyi/OpenBLAS/blob/develop/README.md
      dev_url: https://github.com/xianyi/OpenBLAS

  - name: openblas-devel
    files:
      - include/*blas.h
      - include/lapack*.h
      - include/openblas_config.h
      - lib/cmake/openblas
      - lib/pkgconfig/*blas.pc
      - lib/pkgconfig/lapack*.pc
      - site.cfg
    run_exports:
      - {{ pin_subpackage("libopenblas") }}
      - blas * openblas
    requirements:
      build:
        - {{ stdlib("c") }}
        - {{ compiler("c") }}
        - {{ compiler("fortran") }}
      host:
        - {{ pin_subpackage("libopenblas", exact=True) }}
      run:
        - {{ pin_subpackage("libopenblas", exact=True) }}
        - nomkl
    test:
      commands:
        - test -f ${PREFIX}/lib/pkgconfig/blas.pc                       # [not win]
        - test -f ${PREFIX}/lib/pkgconfig/cblas.pc                      # [not win]
        - test -f ${PREFIX}/lib/pkgconfig/lapack.pc                     # [not win]
        - test -f ${PREFIX}/site.cfg                                    # [not win]
        - if not exist %PREFIX%\\Library\\lib\\openblas.lib exit 1  # [win]
    about:
      home: https://www.openblas.net/
      license: BSD-3-Clause
      license_file: LICENSE
      license_family: BSD
      summary: OpenBLAS headers and libraries for developing software that used OpenBLAS.
      description: OpenBLAS is based on GotoBLAS2 1.13 BSD version.
      doc_url: https://www.openblas.net/
      doc_source_url: https://github.com/xianyi/OpenBLAS/blob/develop/README.md
      dev_url: https://github.com/xianyi/OpenBLAS

  # openblas meta-package. It is better to require openblas-devel or libopenblas
  - name: openblas
    requirements:
      host:
        - {{ pin_subpackage("libopenblas", exact=True) }}
      run:
        - {{ pin_subpackage("libopenblas", exact=True) }}
        - {{ pin_subpackage("openblas-devel", exact=True) }}
        - blas =*=openblas
        - nomkl
    test:
      commands:
        - exit 0

    # mutex package to keep only one blas implementation in a given env
    # Since this package has a non-unique name, blas-1.0-openblas.conda, it is omitted from future updates as they cause issues
    # with overwrites on the PBP. If an update to this package is needed in the future, the name should have a hash added
    # so that it becomes unique per publish.
  - name: blas
    version: 1.0
    build:
      string: openblas
      skip: true  # [not win]
      # track_features doesn't really track anything anymore (blas metapackage
      # dependencies do the same job better). This is still here, though, as it
      # effectively "weighs down" nomkl packages, allowing mkl to take
      # precedence when defaults is the top channel priority.
      track_features:
        - nomkl

  - name: nomkl
    version: 3.0
    build:
      string: "0"
      number: 0
      skip: true  # [not win]
    requirements:
      run:
        - blas * openblas
    about:
      license: BSD-3-clause

about:
  home: https://www.openblas.net/
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - lapack-netlib/LICENSE
  license_family: BSD
  summary: An optimized BLAS library
  description: OpenBLAS is based on GotoBLAS2 1.13 BSD version.
  doc_url: https://www.openblas.net/
  dev_url: https://github.com/xianyi/OpenBLAS

extra:
  recipe-maintainers:
    - gillins
    - groutr
    - jakirkham
    - jschueller
    - isuruf
    - msarahan
    - beckermr
    - chenghlee
